security:
  user:
    name: admin
    password: very_secret_password
  basic:
    enabled: false
management:
  context-path: /admin
graphite:
  host: graphite.host
  port: 2013
  prefix: apps.your_app_name
  frequency-in-sec: 60

---

spring:
  profiles: int

---

spring:
  profiles: prod
